version: "3.7"
services:
  morphicweb:
    hostname: morphicweb
    build:
      context: .
    ports:
      - "5003:80"
      - "9180:9180"
    environment:
      SERVICE_URL: "${SERVICE_URL:-http://localhost:5002/}"
      RECAPTCHA_KEY: "${RECAPTCHA_KEY}"
      MORPHIC_WINDOWS_DOWNLOAD_URL: "${MORPHIC_WINDOWS_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_X86_DOWNLOAD_URL: "${MORPHIC_WINDOWS_X86_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_X64_DOWNLOAD_URL: "${MORPHIC_WINDOWS_X64_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_ARM64_DOWNLOAD_URL: "${MORPHIC_WINDOWS_ARM64_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_APPCAST_URL: "${MORPHIC_WINDOWS_APPCAST_URL}"
      MORPHIC_WINDOWS_X86_APPCAST_URL: "${MORPHIC_WINDOWS_X86_APPCAST_URL}"
      MORPHIC_WINDOWS_X64_APPCAST_URL: "${MORPHIC_WINDOWS_X64_APPCAST_URL}"
      MORPHIC_WINDOWS_ARM64_APPCAST_URL: "${MORPHIC_WINDOWS_ARM64_APPCAST_URL}"
      MORPHIC_WINDOWS_BETA_DOWNLOAD_URL: "${MORPHIC_WINDOWS_BETA_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_BETA_APPCAST_URL: "${MORPHIC_WINDOWS_BETA_APPCAST_URL}"
      MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL: "${MORPHIC_WINDOWS_COMMUNITY_DOWNLOAD_URL}"
      MORPHIC_WINDOWS_COMMUNITY_APPCAST_URL: "${MORPHIC_WINDOWS_COMMUNITY_APPCAST_URL}"
      MORPHIC_MAC_DOWNLOAD_URL: "${MORPHIC_MAC_DOWNLOAD_URL}"
      MORPHIC_MAC_APPCAST_URL: "${MORPHIC_MAC_APPCAST_URL}"
      MORPHIC_MAC_BETA_DOWNLOAD_URL: "${MORPHIC_MAC_BETA_DOWNLOAD_URL}"
      MORPHIC_MAC_BETA_APPCAST_URL: "${MORPHIC_MAC_BETA_APPCAST_URL}"
      MORPHIC_MAC_COMMUNITY_DOWNLOAD_URL: "${MORPHIC_MAC_COMMUNITY_DOWNLOAD_URL}"
      MORPHIC_COMMUNITY_REGISTRATION_URL: "${MORPHIC_COMMUNITY_REGISTRATION_URL}"
    volumes:
    - type: bind
      source: ./www
      target: /MorphicLiteWeb/www
